In [1]:
import pandas as pd
from datetime import datetime, time
import locale

# Trabajo sobre fichadas del Piso de Abajo

## Descarga y trabajo sobre el archivo descargado

1. Una vez descargado el archivo abrirlo en Excel.
2. En Excel seleccionar la columna "B", clic derecho e "insertar". Se debería insertar una columna a la izquierda. Hacerlo 2 veces para tener 2 columnas vacías.
3. En la primera columna vacía, en la primera celda en blanco colocar la siguiente fórmula: =izquierda(A2; 10)
Esto deberia traer la fecha de la celda A2. Arrastrar para todas las celdas.
4. En la segunda columna vacía, en la primera celda en blanco colocar la siguiente fórmula: =derecha(A2;8)
Esto deberia traer la hora de la celda A2. Arrastrar para todas las celdas.

Una vez hecho esto:

- Guardar el archivo como CSV (delimitado por comas) en la **MISMA** carpeta que este archivo.

In [2]:
fichadas = pd.read_csv("./fichadas_abajo.csv", delimiter=";") #Traigo el archivo csv.
fichadas #Acá se muestra el archivo original.

,Time,Fecha,Hora,User ID,Name,Card No.,Device,Door,Event,Verification Method,Access direction
0,2023-06-22 10:57:23,2023-06-22,10:57:23,NaN,NaN,NaN,libertad,Door 1,Close Door,NaN,NaN
1,2023-06-22 10:57:21,2023-06-22,10:57:21,NaN,NaN,NaN,libertad,Door 1,Press button to unlock,NaN,NaN
2,2023-06-22 10:57:21,2023-06-22,10:57:21,NaN,NaN,NaN,libertad,Door 1,Door is unlocked,NaN,NaN
3,2023-06-22 10:56:21,2023-06-22,10:56:21,NaN,NaN,NaN,libertad,Door 1,Close Door,NaN,NaN
4,2023-06-22 10:56:19,2023-06-22,10:56:19,25.0,Barbara Perez,1025,libertad,Door 1,Password Unlock,Password,IN
...,...,...,...,...,...,...,...,...,...,...,...
6474,2023-05-24 07:07:41,2023-05-24,07:07:41,NaN,NaN,NaN,libertad,Door 1,Press button to unlock,NaN,NaN
6475,2023-05-24 07:07:41,2023-05-24,07:07:41,NaN,NaN,NaN,libertad,Door 1,Door is unlocked,NaN,NaN
6476,2023-05-24 07:02:47,2023-05-24,07:02:47,NaN,NaN,NaN,libertad,Door 1,Close Door,NaN,NaN
6477,2023-05-24 07:02:45,2023-05-24,07:02:45,15.0,Rosario Mendoza,1015,libertad,Door 1,Password Unlock,Password,IN
6478,2023-05-24 07:02:45,2023-05-24,07:02:45,NaN,NaN,NaN,libertad,Door 1,Door is unlocked,NaN,NaN

In [3]:
fichadas["Fecha"] = pd.to_datetime(fichadas["Fecha"]) #Convierto la columna "Día" a formato fecha

In [4]:
fecha = fichadas["Fecha"].dropna().unique()
fecha

<DatetimeArray>
['2023-06-22 00:00:00', '2023-06-08 00:00:00', '2023-06-07 00:00:00',
 '2023-06-06 00:00:00', '2023-06-05 00:00:00', '2023-06-04 00:00:00',
 '2023-06-03 00:00:00', '2023-06-02 00:00:00', '2023-06-01 00:00:00',
 '2023-05-31 00:00:00', '2023-05-30 00:00:00', '2023-05-29 00:00:00',
 '2023-05-28 00:00:00', '2023-05-27 00:00:00', '2023-05-26 00:00:00',
 '2023-05-25 00:00:00', '2023-05-24 00:00:00']
Length: 17, dtype: datetime64[ns]

Creo la fichada final en base a la principal donde el indice será "Name", las columnas todos los valores de la columna original "Fecha" (es decir todos los días). Los valores serán los horarios mas tempranos por "Name" en cada "Fecha".

In [5]:
fichadas_final = fichadas.pivot_table(index="Name", columns="Fecha", values="Hora", aggfunc=min)
fichadas_final

Fecha,2023-05-24,2023-05-25,2023-05-26,2023-05-27,2023-05-28,2023-05-29,2023-05-30,2023-05-31,2023-06-01,2023-06-02,2023-06-03,2023-06-04,2023-06-05,2023-06-06,2023-06-07,2023-06-08,2023-06-22
Name,,,,,,,,,,,,,,,,,
Acceso General,10:21:51,19:33:28,02:21:15,04:42:51,01:31:05,09:20:38,10:04:05,02:01:23,04:02:35,00:48:00,00:20:31,12:43:22,05:11:57,03:27:48,02:57:59,10:47:50,10:51:40
Alana Dos Santos,NaN,NaN,NaN,NaN,NaN,07:56:21,07:47:00,08:00:29,08:16:25,07:58:03,NaN,NaN,08:00:48,07:51:30,07:57:39,07:52:07,NaN
Andrea Gargiulo,11:14:04,NaN,NaN,NaN,NaN,12:51:27,10:22:15,10:40:33,10:56:37,12:53:34,NaN,NaN,10:57:22,10:35:09,10:58:27,NaN,10:16:00
Barbara Perez,09:03:05,NaN,NaN,NaN,NaN,09:21:21,12:33:02,09:58:01,08:49:01,09:17:42,NaN,NaN,09:58:33,09:33:38,09:53:01,NaN,09:59:52
Candela Scheiner,09:10:13,NaN,NaN,NaN,NaN,09:08:26,09:06:37,09:08:26,09:19:22,09:08:45,NaN,NaN,09:08:52,08:51:25,09:02:52,09:23:54,NaN
Eduardo Daglio,10:43:19,NaN,NaN,NaN,NaN,09:46:09,10:41:51,NaN,10:15:20,19:29:24,02:21:24,NaN,11:56:12,11:15:15,11:11:22,10:07:50,NaN
Elena Gomez,14:54:21,08:50:08,07:53:36,08:54:49,NaN,10:17:26,10:08:50,16:01:28,15:36:24,NaN,11:15:17,NaN,NaN,14:26:25,14:50:44,NaN,NaN
Elian Callejas,08:17:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Federico Baz,07:10:51,NaN,NaN,NaN,NaN,07:07:19,07:09:29,07:06:15,07:09:38,06:57:40,NaN,NaN,06:22:15,06:59:48,07:03:15,07:03:36,NaN
Federico Lekander,08:54:08,NaN,NaN,NaN,NaN,NaN,08:39:19,08:59:03,NaN,NaN,NaN,NaN,08:44:08,08:55:13,08:49:39,08:51:43,10:55:18
Florencia Roselli,09:52:31,NaN,NaN,NaN,NaN,09:30:08,09:29:17,NaN,09:22:49,09:37:52,NaN,NaN,09:23:29,09:28:23,NaN,NaN,NaN
Gabriel Martino,NaN,12:49:20,09:47:38,16:29:01,NaN,12:38:32,NaN,12:12:03,12:38:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gonzalo F Bonilla,09:01:35,NaN,NaN,NaN,NaN,08:52:23,08:59:50,09:03:28,09:03:19,08:57:33,NaN,NaN,09:05:06,09:03:30,09:01:35,09:03:21,NaN
Ignacio Marquez,09:53:05,NaN,NaN,NaN,NaN,11:30:11,10:57:05,12:57:55,09:19:17,11:10:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jimena Rivera,09:00:11,NaN,NaN,04:42:44,NaN,17:22:29,09:08:50,09:06:34,09:08:55,09:17:59,NaN,NaN,09:06:30,09:24:49,09:09:51,09:05:30,NaN
Karen Carpio,09:05:37,NaN,NaN,NaN,NaN,09:11:24,09:05:58,09:02:21,08:49:35,09:13:19,NaN,NaN,08:50:57,09:13:21,09:10:59,09:05:24,NaN
Karoline Mendez,07:08:28,NaN,NaN,NaN,NaN,07:09:29,07:08:03,07:09:38,07:16:17,07:14:32,NaN,NaN,07:10:29,07:13:10,07:10:32,07:12:30,NaN
Laura Colman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:21:52
Laura Rende,09:32:42,NaN,NaN,NaN,NaN,09:17:22,09:28:33,09:19:31,13:44:14,09:30:11,NaN,NaN,09:17:57,09:27:23,09:22:46,NaN,NaN
Lautaro Bustos,12:28:13,NaN,NaN,NaN,NaN,13:48:26,13:52:20,13:46:21,13:45:13,13:20:22,NaN,NaN,13:55:26,13:57:12,15:55:21,NaN,NaN
Leila Bermudez,14:28:47,NaN,NaN,NaN,NaN,12:51:43,13:52:06,11:40:55,10:38:21,12:25:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Maria Jose Valle,10:02:10,NaN,NaN,NaN,NaN,11:22:41,14:29:11,10:35:07,10:09:22,10:43:19,NaN,NaN,10:11:15,10:03:40,NaN,NaN,10:04:30
Mariana Gatti,08:42:23,NaN,NaN,NaN,NaN,07:50:20,08:20:09,09:27:57,08:35:34,08:32:21,NaN,NaN,08:37:41,09:05:14,06:59:49,10:55:43,NaN
Martin Avolio,08:25:34,NaN,NaN,NaN,NaN,08:31:52,08:02:37,08:02:35,07:58:18,08:09:00,NaN,NaN,07:58:07,08:11:33,08:05:04,08:18:54,NaN
Maximiliano Lopez,12:09:58,NaN,NaN,NaN,NaN,NaN,10:51:24,16:45:54,NaN,11:50:28,NaN,NaN,NaN,NaN,NaN,10:28:19,NaN
Melanie Lucero,NaN,NaN,NaN,NaN,NaN,09:56:09,09:52:47,09:47:21,09:29:01,09:24:33,NaN,NaN,09:47:29,09:28:15,09:43:27,09:29:08,NaN
Melody Lopez,10:04:42,NaN,NaN,NaN,NaN,09:49:38,07:23:32,09:36:51,09:42:08,NaN,NaN,NaN,NaN,09:32:43,09:58:30,NaN,NaN
Mercedes Serkin,09:07:48,NaN,NaN,NaN,NaN,09:03:01,09:05:00,09:03:06,17:38:23,09:01:01,NaN,NaN,NaN,09:03:19,09:09:58,09:00:40,NaN
Micaela Lotz,09:17:23,NaN,NaN,NaN,NaN,09:07:34,09:22:44,09:05:54,09:19:05,09:17:09,NaN,NaN,09:19:18,09:20:39,09:22:52,09:20:36,10:45:39
Personal de obra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18:15:25,NaN,NaN
Philip Marlow,08:53:12,NaN,NaN,NaN,NaN,09:11:30,09:04:08,09:03:16,09:01:57,08:52:28,NaN,NaN,09:11:32,10:02:08,10:11:09,09:10:37,09:58:24
Rosario Mendoza,07:02:45,NaN,NaN,NaN,NaN,NaN,NaN,07:16:46,07:04:05,07:06:57,NaN,NaN,07:06:14,06:47:49,07:09:10,07:05:03,10:05:36
Sebastian Gentini,NaN,NaN,NaN,NaN,NaN,10:54:20,10:21:51,09:39:53,10:23:11,10:23:20,NaN,NaN,09:47:47,10:25:20,09:55:58,10:15:37,10:05:14
clara disalvo,09:53:13,NaN,NaN,NaN,NaN,09:16:26,09:11:04,09:08:22,09:42:19,09:49:15,NaN,NaN,08:52:54,09:13:12,09:46:28,07:53:30,10:24:19

Acá traigo las listas del personal por sector. Estar atento a ingreso de personal nuevo o personal que se va. Avisar asi vamos actualizando este listado.

In [6]:
account = ["Maria Jose Valle", "Rodrigo Fontan", "Alessandra de Castro"]
analytics = ["Sebastian Gentini", "Florencia Roselli"]
bdx = ["Ayelen Rodriguez", "Melanie Lucero", "Karen Carpio", "Martin Avolio", "elian callejas", "Alana Dos Santos", "Paula Corominas"]
billing = ["Melody Lopez"]
claims = ["Federico Baz", "Jimena Rivera", "Karoline Mendez", "Micaela Lotz", "Mercedes Serkin"] #GALATEA LANZA
claims_neg = ["Matias Scarso"]
comercial = ["Barbara Perez", "Ignacio Marquez"]
office = ["Carolina Ledesma", "clara disalvo", "Rosario Mendoza", "Mariana Gatti", "Lautaro Bustos", "elena gomez", "laura colman", "daniela gallardo"]
pagos = ["Eduardo Daglio", "Laura Rende", "Candela Scheiner", "Gonzalo F Bonilla"] 
reimbursement = ["Andrea Gargiulo", "Leila Bermudez", "Gabriela Carvalho", "Sophia Ariganello", "mayara borges", "Lorna Vega", "Barbara Benvindo", "cintia topalian", 
                 "Romina Mariel Lazzaroni", "mariana rios"]
otro = ["Gabriel Martino"]

Voy recorriendo la fichada final por indice. Si el valor del índice (que sería el nombre) está en algunas de las listas de los sectores que se creó antes, entonces me crea una nueva columna llamada "Sector" por cada fila y le da el valor que le corresponde.

Ejemplo: Busco el nombre "Lautaro Bustos", va recorriendo lista por lista hasta que coincida el nombre "Lautaro Bustos" con algún nombre que esté en las listas. En este caso el nombre se encuentra en la lista "Office" por lo que a la nueva columna "Sector" se le asignará el valor "Office".

In [7]:
for indice in fichadas_final.index:
    if indice in account:
        fichadas_final.loc[indice, "Sector"] = "Account"
    elif indice in analytics:
        fichadas_final.loc[indice, "Sector"] = "Analytics"
    elif indice in bdx:
        fichadas_final.loc[indice, "Sector"] = "BDX"
    elif indice in billing:
        fichadas_final.loc[indice, "Sector"] = "Billing"
    elif indice in claims:
        fichadas_final.loc[indice, "Sector"] = "Claims"
    elif indice in claims_neg:
        fichadas_final.loc[indice, "Sector"] = "Claims Neg"
    elif indice in comercial:
        fichadas_final.loc[indice, "Sector"] = "Comercial"
    elif indice in office:
        fichadas_final.loc[indice, "Sector"] = "Office"
    elif indice in pagos:
        fichadas_final.loc[indice, "Sector"] = "Pagos"
    elif indice in reimbursement:
        fichadas_final.loc[indice, "Sector"] = "Reimbursement"
    else:
        fichadas_final.loc[indice, "Sector"] = "Otro"

Este es un ejemplo si vamos filtrando por sectores. En este caso se filtra por la columna "Sector" y que su valor sea "Office". Me debería traer todo el personal que pertenece al sector Office.

In [8]:
fichadas_final[fichadas_final["Sector"] == "Office"]

Fecha,2023-05-24 00:00:00,2023-05-25 00:00:00,2023-05-26 00:00:00,2023-05-27 00:00:00,2023-05-28 00:00:00,2023-05-29 00:00:00,2023-05-30 00:00:00,2023-05-31 00:00:00,2023-06-01 00:00:00,2023-06-02 00:00:00,2023-06-03 00:00:00,2023-06-04 00:00:00,2023-06-05 00:00:00,2023-06-06 00:00:00,2023-06-07 00:00:00,2023-06-08 00:00:00,2023-06-22 00:00:00,Sector
Name,,,,,,,,,,,,,,,,,,
Lautaro Bustos,12:28:13,NaN,NaN,NaN,NaN,13:48:26,13:52:20,13:46:21,13:45:13,13:20:22,NaN,NaN,13:55:26,13:57:12,15:55:21,NaN,NaN,Office
Mariana Gatti,08:42:23,NaN,NaN,NaN,NaN,07:50:20,08:20:09,09:27:57,08:35:34,08:32:21,NaN,NaN,08:37:41,09:05:14,06:59:49,10:55:43,NaN,Office
Rosario Mendoza,07:02:45,NaN,NaN,NaN,NaN,NaN,NaN,07:16:46,07:04:05,07:06:57,NaN,NaN,07:06:14,06:47:49,07:09:10,07:05:03,10:05:36,Office
clara disalvo,09:53:13,NaN,NaN,NaN,NaN,09:16:26,09:11:04,09:08:22,09:42:19,09:49:15,NaN,NaN,08:52:54,09:13:12,09:46:28,07:53:30,10:24:19,Office

Con el próximo código podemos ver la tabla final y en la última columna aparece "Sector" y el sector correspondiente a cada personal.

In [9]:
fichadas_final.head()

Fecha,2023-05-24 00:00:00,2023-05-25 00:00:00,2023-05-26 00:00:00,2023-05-27 00:00:00,2023-05-28 00:00:00,2023-05-29 00:00:00,2023-05-30 00:00:00,2023-05-31 00:00:00,2023-06-01 00:00:00,2023-06-02 00:00:00,2023-06-03 00:00:00,2023-06-04 00:00:00,2023-06-05 00:00:00,2023-06-06 00:00:00,2023-06-07 00:00:00,2023-06-08 00:00:00,2023-06-22 00:00:00,Sector
Name,,,,,,,,,,,,,,,,,,
Acceso General,10:21:51,19:33:28,02:21:15,04:42:51,01:31:05,09:20:38,10:04:05,02:01:23,04:02:35,00:48:00,00:20:31,12:43:22,05:11:57,03:27:48,02:57:59,10:47:50,10:51:40,Otro
Alana Dos Santos,NaN,NaN,NaN,NaN,NaN,07:56:21,07:47:00,08:00:29,08:16:25,07:58:03,NaN,NaN,08:00:48,07:51:30,07:57:39,07:52:07,NaN,BDX
Andrea Gargiulo,11:14:04,NaN,NaN,NaN,NaN,12:51:27,10:22:15,10:40:33,10:56:37,12:53:34,NaN,NaN,10:57:22,10:35:09,10:58:27,NaN,10:16:00,Reimbursement
Barbara Perez,09:03:05,NaN,NaN,NaN,NaN,09:21:21,12:33:02,09:58:01,08:49:01,09:17:42,NaN,NaN,09:58:33,09:33:38,09:53:01,NaN,09:59:52,Comercial
Candela Scheiner,09:10:13,NaN,NaN,NaN,NaN,09:08:26,09:06:37,09:08:26,09:19:22,09:08:45,NaN,NaN,09:08:52,08:51:25,09:02:52,09:23:54,NaN,Pagos

En el siguiente código cambio el nombre de las columnas de tipo "fechas" a "texto/string" y reemplazo los "00:00:00" por espacios vacios.

In [10]:
fichadas_final.columns = fichadas_final.columns.astype(str).str.replace(" 00:00:00", "")

Busco el mes actual para agregarlo al nombre de los archivos.

In [11]:
# Establecer la configuración regional en español para que el mes se registre en español
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

# Obtener la fecha actual
fecha_actual = datetime.now()

# Obtener el nombre del mes actual
nombre_mes_actual = fecha_actual.strftime("%B").capitalize()

Creo los distintos archivos según cada sector y hago que se descarguen.

In [12]:
#ARCHIVO GENERAL
nombre_archivo = f"fichadas Abajo {nombre_mes_actual}.xlsx"
fichadas_final.to_excel(nombre_archivo, index=True)

#ACCOUNT
fichadas_account = fichadas_final[fichadas_final["Sector"] == "Account"]
nombre_account = f"Fichadas Abajo Account {nombre_mes_actual}.xlsx"
fichadas_account.to_excel(nombre_account, index=True)

#Analytics
fichadas_analytics = fichadas_final[fichadas_final["Sector"] == "Analytics"]
nombre_analytics = f"Fichadas Abajo Analytics {nombre_mes_actual}.xlsx"
fichadas_analytics.to_excel(nombre_analytics, index=True)

#BDX
fichadas_BDX = fichadas_final[fichadas_final["Sector"] == "BDX"]
nombre_BDX = f"Fichadas Abajo BDX {nombre_mes_actual}.xlsx"
fichadas_BDX.to_excel(nombre_BDX, index=True)

#Billing
fichadas_Billing = fichadas_final[fichadas_final["Sector"] == "Billing"]
nombre_Billing = f"Fichadas Abajo Billing {nombre_mes_actual}.xlsx"
fichadas_Billing.to_excel(nombre_Billing, index=True)

#Claims
fichadas_Claims = fichadas_final[fichadas_final["Sector"] == "Claims"]
nombre_Claims = f"Fichadas Abajo Claims {nombre_mes_actual}.xlsx"
fichadas_Claims.to_excel(nombre_Claims, index=True)

#Comercial
fichadas_Comercial = fichadas_final[fichadas_final["Sector"] == "Comercial"]
nombre_Comercial = f"Fichadas Abajo Comercial {nombre_mes_actual}.xlsx"
fichadas_Comercial.to_excel(nombre_Comercial, index=True)

#Office
fichadas_Office = fichadas_final[fichadas_final["Sector"] == "Office"]
nombre_Office = f"Fichadas Abajo Office {nombre_mes_actual}.xlsx"
fichadas_Office.to_excel(nombre_Office, index=True)

#Pagos
fichadas_Pagos = fichadas_final[fichadas_final["Sector"] == "Pagos"]
nombre_Pagos = f"Fichadas Abajo Pagos {nombre_mes_actual}.xlsx"
fichadas_Pagos.to_excel(nombre_Pagos, index=True)

#Reimbursement
fichadas_Reimbursement = fichadas_final[fichadas_final["Sector"] == "Reimbursement"]
nombre_Reimbursement = f"Fichadas Abajo Reimbursement {nombre_mes_actual}.xlsx"
fichadas_Reimbursement.to_excel(nombre_Reimbursement, index=True)

#Otro
fichadas_Otro = fichadas_final[fichadas_final["Sector"] == "Otro"]
nombre_Otro = f"Fichadas Abajo Otro {nombre_mes_actual}.xlsx"
fichadas_Otro.to_excel(nombre_Reimbursement, index=True)